# Generated by Django 4.1.3 on 2022-11-19 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('fae45049-d22a-4810-b4f4-d8097dc85128'), editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('profitability', models.BooleanField()),
                ('activity', models.BooleanField()),
                ('liquidity', models.BooleanField()),
                ('debt', models.BooleanField()),
                ('market', models.BooleanField()),
                ('label', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
