# Generated by Django 4.1.3 on 2022-11-19 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d23da128-eb00-43dc-bd19-b76fe1c2faa9'), editable=False, unique=True),
        ),
    ]
