# Generated by Django 4.1.3 on 2022-12-02 03:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('name_with_type', models.CharField(max_length=255)),
                ('code', models.IntegerField()),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('name_with_type', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('path_with_type', models.CharField(max_length=1000)),
                ('code', models.IntegerField()),
                ('parent_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='address.city')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('name_with_type', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('path_with_type', models.CharField(max_length=1000)),
                ('code', models.IntegerField()),
                ('parent_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='address.district')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
