# Generated by Django 4.1.3 on 2022-12-02 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_city_created_at_alter_district_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='updated_at',
        ),
    ]
