# Generated by Django 4.1.3 on 2022-12-02 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('user', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_line', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.city', to_field='key')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.district', to_field='key')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='key')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.ward', to_field='key')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
