# Generated by Django 4.1.3 on 2022-11-19 04:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99da98c7-2661-4d30-b822-0816408c4fdf'), editable=False),
        ),
    ]
