# Generated by Django 4.1.3 on 2022-11-19 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stockcode_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('466103a0-0303-47c6-b34c-cf5a1995c434'), editable=False),
        ),
        migrations.CreateModel(
            name='StockPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('466103a0-0303-47c6-b34c-cf5a1995c434'), editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('net_profit', models.BigIntegerField()),
                ('total_asset', models.BigIntegerField()),
                ('revenue', models.BigIntegerField()),
                ('current_asset', models.BigIntegerField()),
                ('current_debt', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('price', models.IntegerField()),
                ('eps', models.IntegerField()),
                ('label', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
