# Generated by Django 4.1.3 on 2022-11-19 06:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stockcode_uid_stockperday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fd6e772e-63db-49a8-80f7-42ac193a0426'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockperday',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockcode', to_field='uid'),
        ),
        migrations.AlterField(
            model_name='stockperday',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fd6e772e-63db-49a8-80f7-42ac193a0426'), editable=False, unique=True),
        ),
    ]
