# Generated by Django 4.1.3 on 2022-11-19 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stockcode_uid_alter_stockperday_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fae45049-d22a-4810-b4f4-d8097dc85128'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockperday',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fae45049-d22a-4810-b4f4-d8097dc85128'), editable=False, unique=True),
        ),
    ]
