# Generated by Django 4.1.3 on 2022-11-19 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stockcode_uid_alter_stockperday_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6f383ef6-f3a6-4fe0-9f53-e0539186695a'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockperday',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('6f383ef6-f3a6-4fe0-9f53-e0539186695a'), editable=False, unique=True),
        ),
    ]
