# Generated by Django 4.1.3 on 2022-11-19 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stockcode_uid_alter_stockperday_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e7d70287-e476-40cb-b9cf-b2bae8ec09fa'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockperday',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e7d70287-e476-40cb-b9cf-b2bae8ec09fa'), editable=False, unique=True),
        ),
    ]
