# Generated by Django 4.1.3 on 2022-11-19 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stockcode_uid_alter_stockperday_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcode',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockperday',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
